version: "3.8"

services:
  web:
    image: php:7.2.2-apache
    container_name: messenger_local
    volumes:
      - ./html/:/var/www/html/local/
      - ./build/:/var/www/html/build/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true